### ISSUE TITLE
data/conceptnet/conceptnet_vocab_definition.jsonl文件

### ISSUE THREAD

**Issue by Yueqing-Sun** [gychant/CSKMTermDefn#1]
您好，我在寒假时读了这篇论文，觉得想法非常棒，非常感谢您分享源码！
由于防火墙的限制，我不能正常使用wiktionaryparser爬取到词的定义，能不能拜托您给我发一下“data/conceptnet/conceptnet_vocab_definition.jsonl”文件呀，我的邮箱：990795617@qq.com，非常感谢！

**Comment by gychant** [comment]
Hello,

I emailed you a copy of the data.

Thanks!

**Comment by Yueqing-Sun** [comment]
> Hello,
> 
> I emailed you a copy of the data.
> 
> Thanks!

I have received the data you emailed, many thanks!
